name: camera_webrtc
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^3.1.4
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.8.0
  camera_platform_interface:
    path: ../camera_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1
  very_good_analysis: ^2.0.4
  

flutter:
